# Exercise 02 -  OLAP Cubes - Grouping Sets

Start by connecting to the database by running the cells below. If you are coming back to this exercise, then uncomment and run the first cell to recreate the database. If you recently completed the slicing and dicing exercise, then skip to the second cell.

In [ ]:
# !PGPASSWORD=student createdb -h 127.0.0.1 -U student pagila_star
# !PGPASSWORD=student psql -q -h 127.0.0.1 -U student -d pagila_star -f Data/pagila-star.sql

### Connect to the local database where Pagila is loaded

In [1]:
import sql
%load_ext sql

DB_ENDPOINT = "127.0.0.1"
DB = 'pagila_star'
DB_USER = 'abbas'
DB_PASSWORD = 'root'
DB_PORT = '5432'

# postgresql://username:password@host:port/database
conn_string = "postgresql://{}:{}@{}:{}/{}" \
                        .format(DB_USER, DB_PASSWORD, DB_ENDPOINT, DB_PORT, DB)

print(conn_string)
%sql $conn_string

postgresql://abbas:root@127.0.0.1:5432/pagila_star

'Connected: abbas@pagila_star'

### Star Schema

<img src="pagila-star.png" width="50%"/>

# Grouping Sets
- It happens often that for 3 dimensions, you want to aggregate a fact:
    - by nothing (total)
    - then by the 1st dimension
    - then by the 2nd 
    - then by the 3rd 
    - then by the 1st and 2nd
    - then by the 2nd and 3rd
    - then by the 1st and 3rd
    - then by the 1st and 2nd and 3rd
    
- Since this is very common, and in all cases, we are iterating through all the fact table anyhow, there is a more clever way to do that using the SQL grouping statement "GROUPING SETS"

## Total Revenue

TODO: Write a query that calculates total revenue (sales_amount)

In [4]:
%%sql
SELECT sum(sales_amount) as revenue 
FROM factSales;

 * postgresql://abbas:***@127.0.0.1:5432/pagila_star
1 rows affected.

[(Decimal('134833.02'),)]

## Revenue by Country
TODO: Write a query that calculates total revenue (sales_amount) by country

In [7]:
%%sql
SELECT dc.country, sum(fs.sales_amount) as revenue
FROM dimcustomer dc 
JOIN factsales fs ON (dc.customer_key = fs.customer_key)
GROUP BY dc.country;

 * postgresql://abbas:***@127.0.0.1:5432/pagila_star
108 rows affected.

[('Thailand', Decimal('838.08')),
 ('Virgin Islands, U.S.', Decimal('245.36')),
 ('Bangladesh', Decimal('804.10')),
 ('Indonesia', Decimal('3020.66')),
 ('Faroe Islands', Decimal('229.44')),
 ('Italy', Decimal('1662.22')),
 ('Venezuela', Decimal('1366.60')),
 ('Oman', Decimal('375.00')),
 ('Cameroon', Decimal('400.92')),
 ('Czech Republic', Decimal('267.42')),
 ('Sweden', Decimal('289.32')),
 ('Congo, The Democratic Republic of the', Decimal('425.00')),
 ('United Kingdom', Decimal('1849.60')),
 ('Dominican Republic', Decimal('636.46')),
 ('Cambodia', Decimal('382.94')),
 ('Germany', Decimal('1662.08')),
 ('American Samoa', Decimal('143.60')),
 ('Canada', Decimal('1187.26')),
 ('Sri Lanka', Decimal('233.40')),
 ('Brunei', Decimal('227.30')),
 ('South Korea', Decimal('1149.30')),
 ('Anguilla', Decimal('213.30')),
 ('Finland', Decimal('203.48')),
 ('Colombia', Decimal('1418.82')),
 ('Saint Vincent and the Grenadines', Decimal('193.50')),
 ('Runion', Decimal('433.08')),
 ('Ukraine', Decimal('1460.84')),
 ('Saudi Arabia', Decimal('1047.58')),
 ('Argentina', Decimal('2868.96')),
 ('Liechtenstein', Decimal('229.44')),
 ('Latvia', Decimal('524.80')),
 ('North Korea', Decimal('227.38')),
 ('Holy See (Vatican City State)', Decimal('305.32')),
 ('Azerbaijan', Decimal('490.86')),
 ('Greece', Decimal('464.92')),
 ('Egypt', Decimal('1388.78')),
 ('Afghanistan', Decimal('135.64')),
 ('Chad', Decimal('271.36')),
 ('Puerto Rico', Decimal('508.78')),
 ('India', Decimal('13260.54')),
 ('Iran', Decimal('1901.50')),
 ('French Polynesia', Decimal('470.92')),
 ('Chile', Decimal('656.58')),
 ('Algeria', Decimal('766.20')),
 ('Gambia', Decimal('259.40')),
 ('France', Decimal('748.08')),
 ('Estonia', Decimal('231.40')),
 ('Vietnam', Decimal('1492.56')),
 ('Slovakia', Decimal('179.48')),
 ('Israel', Decimal('844.02')),
 ('South Africa', Decimal('2408.30')),
 ('Nauru', Decimal('297.38')),
 ('Peru', Decimal('937.76')),
 ('Senegal', Decimal('201.50')),
 ('Kenya', Decimal('506.92')),
 ('Malaysia', Decimal('738.30')),
 ('Kazakstan', Decimal('396.96')),
 ('Zambia', Decimal('269.34')),
 ('Hong Kong', Decimal('285.40')),
 ('Kuwait', Decimal('223.48')),
 ('Madagascar', Decimal('187.56')),
 ('Yugoslavia', Decimal('518.86')),
 ('Japan', Decimal('6943.48')),
 ('Philippines', Decimal('4762.64')),
 ('Tuvalu', Decimal('241.48')),
 ('United States', Decimal('8220.64')),
 ('Iraq', Decimal('223.46')),
 ('Turkey', Decimal('3324.24')),
 ('Nigeria', Decimal('3022.96')),
 ('Mozambique', Decimal('688.40')),
 ('Switzerland', Decimal('504.78')),
 ('New Zealand', Decimal('185.52')),
 ('Ecuador', Decimal('780.26')),
 ('Hungary', Decimal('223.42')),
 ('China', Decimal('11605.46')),
 ('Armenia', Decimal('237.50')),
 ('Belarus', Decimal('554.68')),
 ('Pakistan', Decimal('1051.44')),
 ('Russian Federation', Decimal('6091.74')),
 ('Netherlands', Decimal('1173.32')),
 ('Romania', Decimal('470.76')),
 ('Paraguay', Decimal('550.76')),
 ('Brazil', Decimal('6401.04')),
 ('Austria', Decimal('614.44')),
 ('Bolivia', Decimal('367.06')),
 ('Ethiopia', Decimal('183.54')),
 ('Angola', Decimal('430.96')),
 ('Bahrain', Decimal('225.50')),
 ('Yemen', Decimal('1021.66')),
 ('Lithuania', Decimal('147.52')),
 ('Bulgaria', Decimal('409.00')),
 ('Spain', Decimal('1213.16')),
 ('Turkmenistan', Decimal('273.46')),
 ('Tunisia', Decimal('157.54')),
 ('Sudan', Decimal('454.92')),
 ('United Arab Emirates', Decimal('666.32')),
 ('Malawi', Decimal('247.44')),
 ('Morocco', Decimal('614.58')),
 ('Moldova', Decimal('255.32')),
 ('Myanmar', Decimal('388.96')),
 ('Mexico', Decimal('6614.08')),
 ('Tonga', Decimal('147.64')),
 ('Nepal', Decimal('233.56')),
 ('Tanzania', Decimal('682.34')),
 ('Taiwan', Decimal('2421.88')),
 ('Poland', Decimal('1755.94')),
 ('French Guiana', Decimal('207.56')),
 ('Greenland', Decimal('275.32'))]

## Revenue by Month
TODO: Write a query that calculates total revenue (sales_amount) by month

In [8]:
%%sql
SELECT dd.month, sum(fs.sales_amount) as revenue
FROM dimdate dd 
JOIN factsales fs ON (dd.date_key = fs.date_key)
GROUP BY dd.month;

 * postgresql://abbas:***@127.0.0.1:5432/pagila_star
7 rows affected.

[(7, Decimal('9760.54')),
 (1, Decimal('7880.31')),
 (5, Decimal('11889.42')),
 (4, Decimal('39297.01')),
 (2, Decimal('19781.91')),
 (6, Decimal('10920.42')),
 (3, Decimal('35303.41'))]

## Revenue by Month & Country
TODO: Write a query that calculates total revenue (sales_amount) by month and country. Sort the data by month, country, and revenue in descending order. The first few rows of your output should match the table below.

In [9]:
%%sql
SELECT dd.month, dc.country, sum(fs.sales_amount) as revenue
FROM dimdate dd 
JOIN factsales fs ON (dd.date_key = fs.date_key)
JOIN dimcustomer dc ON (fs.customer_key = fs.customer_key)
GROUP BY dd.month, dc.country;

 * postgresql://abbas:***@127.0.0.1:5432/pagila_star
756 rows affected.

[(5, 'Myanmar', Decimal('23778.84')),
 (7, 'Myanmar', Decimal('19521.08')),
 (5, 'Puerto Rico', Decimal('23778.84')),
 (3, 'Iran', Decimal('282427.28')),
 (5, 'Nepal', Decimal('11889.42')),
 (3, 'Germany', Decimal('247123.87')),
 (4, 'New Zealand', Decimal('39297.01')),
 (6, 'United Arab Emirates', Decimal('32761.26')),
 (4, 'Cameroon', Decimal('78594.02')),
 (2, 'Holy See (Vatican City State)', Decimal('19781.91')),
 (7, 'India', Decimal('585632.40')),
 (5, 'Nauru', Decimal('11889.42')),
 (6, 'Indonesia', Decimal('152885.88')),
 (5, 'Sweden', Decimal('11889.42')),
 (1, 'Holy See (Vatican City State)', Decimal('7880.31')),
 (6, 'Brazil', Decimal('305771.76')),
 (4, 'Paraguay', Decimal('117891.03')),
 (1, 'Pakistan', Decimal('39401.55')),
 (5, 'Dominican Republic', Decimal('35668.26')),
 (5, 'Canada', Decimal('59447.10')),
 (3, 'Faroe Islands', Decimal('35303.41')),
 (7, 'Kazakstan', Decimal('19521.08')),
 (7, 'Runion', Decimal('9760.54')),
 (3, 'Lithuania', Decimal('35303.41')),
 (4, 'Brunei', Decimal('39297.01')),
 (7, 'Anguilla', Decimal('9760.54')),
 (6, 'Paraguay', Decimal('32761.26')),
 (6, 'Yugoslavia', Decimal('21840.84')),
 (3, 'Malaysia', Decimal('105910.23')),
 (4, 'Lithuania', Decimal('39297.01')),
 (3, 'Peru', Decimal('141213.64')),
 (7, 'Russian Federation', Decimal('273295.12')),
 (4, 'Peru', Decimal('157188.04')),
 (5, 'Turkey', Decimal('178341.30')),
 (7, 'Faroe Islands', Decimal('9760.54')),
 (6, 'Germany', Decimal('76442.94')),
 (3, 'Poland', Decimal('282427.28')),
 (2, 'Angola', Decimal('39563.82')),
 (7, 'Kenya', Decimal('19521.08')),
 (2, 'Turkey', Decimal('296728.65')),
 (6, 'American Samoa', Decimal('10920.42')),
 (3, 'Canada', Decimal('176517.05')),
 (1, 'Myanmar', Decimal('15760.62')),
 (4, 'Kenya', Decimal('78594.02')),
 (7, 'Dominican Republic', Decimal('29281.62')),
 (5, 'Mozambique', Decimal('35668.26')),
 (5, 'Chad', Decimal('11889.42')),
 (1, 'Saint Vincent and the Grenadines', Decimal('7880.31')),
 (4, 'Ethiopia', Decimal('39297.01')),
 (3, 'Bangladesh', Decimal('105910.23')),
 (2, 'Philippines', Decimal('395638.20')),
 (5, 'Gambia', Decimal('11889.42')),
 (1, 'Philippines', Decimal('157606.20')),
 (6, 'Slovakia', Decimal('10920.42')),
 (6, 'Puerto Rico', Decimal('21840.84')),
 (6, 'Bulgaria', Decimal('21840.84')),
 (7, 'Liechtenstein', Decimal('9760.54')),
 (7, 'Tunisia', Decimal('9760.54')),
 (4, 'France', Decimal('157188.04')),
 (3, 'Nigeria', Decimal('458944.33')),
 (1, 'France', Decimal('31521.24')),
 (1, 'Armenia', Decimal('7880.31')),
 (4, 'Pakistan', Decimal('196485.05')),
 (1, 'Tanzania', Decimal('23640.93')),
 (1, 'Venezuela', Decimal('55162.17')),
 (3, 'Mexico', Decimal('1059102.30')),
 (6, 'Senegal', Decimal('10920.42')),
 (6, 'Israel', Decimal('43681.68')),
 (5, 'Kuwait', Decimal('11889.42')),
 (4, 'Brazil', Decimal('1100316.28')),
 (5, 'Iraq', Decimal('11889.42')),
 (2, 'Iraq', Decimal('19781.91')),
 (4, 'Mozambique', Decimal('117891.03')),
 (4, 'Belarus', Decimal('78594.02')),
 (3, 'Slovakia', Decimal('35303.41')),
 (2, 'Bangladesh', Decimal('59345.73')),
 (6, 'Chad', Decimal('10920.42')),
 (7, 'South Africa', Decimal('107365.94')),
 (7, 'Mexico', Decimal('292816.20')),
 (3, 'Bolivia', Decimal('70606.82')),
 (1, 'Gambia', Decimal('7880.31')),
 (7, 'Belarus', Decimal('19521.08')),
 (3, 'Virgin Islands, U.S.', Decimal('35303.41')),
 (4, 'Cambodia', Decimal('78594.02')),
 (1, 'Morocco', Decimal('23640.93')),
 (2, 'Russian Federation', Decimal('553893.48')),
 (7, 'Yugoslavia', Decimal('19521.08')),
 (6, 'Colombia', Decimal('65522.52')),
 (5, 'Cameroon', Decimal('23778.84')),
 (4, 'Puerto Rico', Decimal('78594.02')),
 (7, 'Chad', Decimal('9760.54')),
 (7, 'Holy See (Vatican City State)', Decimal('9760.54')),
 (3, 'United Kingdom', Decimal('317730.69')),
 (2, 'Thailand', Decimal('59345.73')),
 (4, 'Israel', Decimal('157188.04')),
 (3, 'Tonga', Decimal('35303.41')),
 (6, 'Ecuador', Decimal('32761.26')),
 (1, 'Slovakia', Decimal('7880.31')),
 (7, 'Malawi', Decimal('9760.54')),
 (2, 'Bahrain', Decimal('19781.91')),
 (5, 'Saudi Arabia', Decimal('59447.10')),
 (2, 'Nauru', Decimal('19781.91')),
 (5, 'United States', Decimal('428019.12')),
 (3, 'Pakistan', Decimal('176517.05')),
 (2, 'Slovakia', Decimal('19781.91')),
 (2, 'Switzerland', Decimal('59345.73')),
 (6, 'Angola', Decimal('21840.84')),
 (3, 'Venezuela', Decimal('247123.87')),
 (1, 'North Korea', Decimal('7880.31')),
 (7, 'Finland', Decimal('9760.54')),
 (5, 'Madagascar', Decimal('11889.42')),
 (6, 'Chile', Decimal('32761.26')),
 (2, 'Congo, The Democratic Republic of the', Decimal('39563.82')),
 (2, 'Peru', Decimal('79127.64')),
 (1, 'Chile', Decimal('23640.93')),
 (2, 'Tanzania', Decimal('59345.73')),
 (7, 'Argentina', Decimal('126887.02')),
 (3, 'Bulgaria', Decimal('70606.82')),
 (6, 'Saudi Arabia', Decimal('54602.10')),
 (4, 'United Arab Emirates', Decimal('117891.03')),
 (3, 'Colombia', Decimal('211820.46')),
 (1, 'Cambodia', Decimal('15760.62')),
 (3, 'Taiwan', Decimal('353034.10')),
 (7, 'American Samoa', Decimal('9760.54')),
 (3, 'Italy', Decimal('247123.87')),
 (3, 'Sweden', Decimal('35303.41')),
 (1, 'Poland', Decimal('63042.48')),
 (1, 'Sudan', Decimal('15760.62')),
 (4, 'Mexico', Decimal('1178910.30')),
 (7, 'Ecuador', Decimal('29281.62')),
 (5, 'Azerbaijan', Decimal('23778.84')),
 (3, 'Zambia', Decimal('35303.41')),
 (1, 'Algeria', Decimal('23640.93')),
 (3, 'Liechtenstein', Decimal('35303.41')),
 (3, 'Runion', Decimal('35303.41')),
 (3, 'Hungary', Decimal('35303.41')),
 (6, 'United Kingdom', Decimal('98283.78')),
 (1, 'French Polynesia', Decimal('15760.62')),
 (5, 'North Korea', Decimal('11889.42')),
 (7, 'Tonga', Decimal('9760.54')),
 (4, 'Runion', Decimal('39297.01')),
 (6, 'Latvia', Decimal('21840.84')),
 (6, 'Kenya', Decimal('21840.84')),
 (4, 'Moldova', Decimal('39297.01')),
 (4, 'Chile', Decimal('117891.03')),
 (3, 'Mozambique', Decimal('105910.23')),
 (3, 'Nepal', Decimal('35303.41')),
 (2, 'Malawi', Decimal('19781.91')),
 (6, 'Iraq', Decimal('10920.42')),
 (6, 'China', Decimal('578782.26')),
 (7, 'Puerto Rico', Decimal('19521.08')),
 (3, 'China', Decimal('1871080.73')),
 (1, 'United Kingdom', Decimal('70922.79')),
 (6, 'Pakistan', Decimal('54602.10')),
 (6, 'Netherlands', Decimal('54602.10')),
 (1, 'Ecuador', Decimal('23640.93')),
 (6, 'Tanzania', Decimal('32761.26')),
 (3, 'Anguilla', Decimal('35303.41')),
 (1, 'India', Decimal('472818.60')),
 (3, 'Switzerland', Decimal('105910.23')),
 (2, 'Yemen', Decimal('79127.64')),
 (4, 'Bahrain', Decimal('39297.01')),
 (7, 'Madagascar', Decimal('9760.54')),
 (4, 'Sri Lanka', Decimal('39297.01')),
 (3, 'Belarus', Decimal('70606.82')),
 (6, 'Iran', Decimal('87363.36')),
 (1, 'Oman', Decimal('15760.62')),
 (6, 'Saint Vincent and the Grenadines', Decimal('10920.42')),
 (4, 'Gambia', Decimal('39297.01')),
 (5, 'Ecuador', Decimal('35668.26')),
 (5, 'Algeria', Decimal('35668.26')),
 (7, 'Austria', Decimal('29281.62')),
 (7, 'Italy', Decimal('68323.78')),
 (2, 'North Korea', Decimal('19781.91')),
 (6, 'Romania', Decimal('21840.84')),
 (3, 'French Polynesia', Decimal('70606.82')),
 (2, 'Sweden', Decimal('19781.91')),
 (2, 'Ethiopia', Decimal('19781.91')),
 (7, 'United Arab Emirates', Decimal('29281.62')),
 (2, 'Israel', Decimal('79127.64')),
 (4, 'Taiwan', Decimal('392970.10')),
 (7, 'Romania', Decimal('19521.08')),
 (7, 'Czech Republic', Decimal('9760.54')),
 (1, 'Mexico', Decimal('236409.30')),
 (3, 'Madagascar', Decimal('35303.41')),
 (4, 'Thailand', Decimal('117891.03')),
 (1, 'Malawi', Decimal('7880.31')),
 (7, 'Bahrain', Decimal('9760.54')),
 (1, 'Sri Lanka', Decimal('7880.31')),
 (3, 'Cambodia', Decimal('70606.82')),
 (7, 'Zambia', Decimal('9760.54')),
 (1, 'Kazakstan', Decimal('15760.62')),
 (7, 'Cambodia', Decimal('19521.08')),
 (5, 'Holy See (Vatican City State)', Decimal('11889.42')),
 (2, 'Zambia', Decimal('19781.91')),
 (7, 'Chile', Decimal('29281.62')),
 (2, 'Spain', Decimal('98909.55')),
 (5, 'Senegal', Decimal('11889.42')),
 (5, 'New Zealand', Decimal('11889.42')),
 (2, 'Egypt', Decimal('118691.46')),
 (4, 'Argentina', Decimal('510861.13')),
 (5, 'Pakistan', Decimal('59447.10')),
 (7, 'Egypt', Decimal('58563.24')),
 (2, 'Romania', Decimal('39563.82')),
 (2, 'Kuwait', Decimal('19781.91')),
 (2, 'Morocco', Decimal('59345.73')),
 (4, 'Senegal', Decimal('39297.01')),
 (6, 'Poland', Decimal('87363.36')),
 (6, 'Oman', Decimal('21840.84')),
 (4, 'Yemen', Decimal('157188.04')),
 (2, 'Canada', Decimal('98909.55')),
 (5, 'Peru', Decimal('47557.68')),
 (1, 'Bahrain', Decimal('7880.31')),
 (2, 'Virgin Islands, U.S.', Decimal('19781.91')),
 (6, 'Nauru', Decimal('10920.42')),
 (4, 'Estonia', Decimal('39297.01')),
 (2, 'Argentina', Decimal('257164.83')),
 (1, 'Puerto Rico', Decimal('15760.62')),
 (4, 'Turkey', Decimal('589455.15')),
 (4, 'Czech Republic', Decimal('39297.01')),
 (7, 'Israel', Decimal('39042.16')),
 (7, 'Morocco', Decimal('29281.62')),
 (2, 'Belarus', Decimal('39563.82')),
 (6, 'Mexico', Decimal('327612.60')),
 (4, 'Nepal', Decimal('39297.01')),
 (7, 'Philippines', Decimal('195210.80')),
 (2, 'Armenia', Decimal('19781.91')),
 (4, 'Armenia', Decimal('39297.01')),
 (6, 'Anguilla', Decimal('10920.42')),
 (1, 'Nauru', Decimal('7880.31')),
 (3, 'Sudan', Decimal('70606.82')),
 (5, 'Brunei', Decimal('11889.42')),
 (3, 'Morocco', Decimal('105910.23')),
 (7, 'Brunei', Decimal('9760.54')),
 (2, 'Bulgaria', Decimal('39563.82')),
 (3, 'Kazakstan', Decimal('70606.82')),
 (5, 'Hungary', Decimal('11889.42')),
 (6, 'Czech Republic', Decimal('10920.42')),
 (7, 'Peru', Decimal('39042.16')),
 (4, 'Sudan', Decimal('78594.02')),
 (2, 'French Guiana', Decimal('19781.91')),
 (7, 'Senegal', Decimal('9760.54')),
 (1, 'Moldova', Decimal('7880.31')),
 (1, 'Kenya', Decimal('15760.62')),
 (6, 'India', Decimal('655225.20')),
 (7, 'United Kingdom', Decimal('87844.86')),
 (1, 'Ukraine', Decimal('47281.86')),
 (4, 'Holy See (Vatican City State)', Decimal('39297.01')),
 (5, 'Zambia', Decimal('11889.42')),
 (4, 'North Korea', Decimal('39297.01')),
 (4, 'Bangladesh', Decimal('117891.03')),
 (3, 'Greenland', Decimal('35303.41')),
 (5, 'Kazakstan', Decimal('23778.84')),
 (4, 'Indonesia', Decimal('550158.14')),
 (3, 'Dominican Republic', Decimal('105910.23')),
 (7, 'Taiwan', Decimal('97605.40')),
 (4, 'Sweden', Decimal('39297.01')),
 (7, 'Turkmenistan', Decimal('9760.54')),
 (5, 'Yemen', Decimal('47557.68')),
 (3, 'South Korea', Decimal('176517.05')),
 (1, 'Finland', Decimal('7880.31')),
 (2, 'United Arab Emirates', Decimal('59345.73')),
 (2, 'Germany', Decimal('138473.37')),
 (5, 'Chile', Decimal('35668.26')),
 (5, 'Ukraine', Decimal('71336.52')),
 (4, 'Tuvalu', Decimal('39297.01')),
 (4, 'Ecuador', Decimal('117891.03')),
 (6, 'South Korea', Decimal('54602.10')),
 (1, 'Kuwait', Decimal('7880.31')),
 (3, 'Armenia', Decimal('35303.41')),
 (4, 'Greenland', Decimal('39297.01')),
 (1, 'Estonia', Decimal('7880.31')),
 (5, 'Yugoslavia', Decimal('23778.84')),
 (4, 'Iran', Decimal('314376.08')),
 (5, 'Egypt', Decimal('71336.52')),
 (3, 'United States', Decimal('1270922.76')),
 (4, 'Iraq', Decimal('39297.01')),
 (5, 'Brazil', Decimal('332903.76')),
 (2, 'American Samoa', Decimal('19781.91')),
 (1, 'Nigeria', Decimal('102444.03')),
 (4, 'Austria', Decimal('117891.03')),
 (4, 'Saint Vincent and the Grenadines', Decimal('39297.01')),
 (1, 'United Arab Emirates', Decimal('23640.93')),
 (7, 'French Polynesia', Decimal('19521.08')),
 (5, 'Greenland', Decimal('11889.42')),
 (2, 'Algeria', Decimal('59345.73')),
 (6, 'Gambia', Decimal('10920.42')),
 (6, 'United States', Decimal('393135.12')),
 (3, 'Tunisia', Decimal('35303.41')),
 (3, 'Turkey', Decimal('529551.15')),
 (3, 'Chad', Decimal('35303.41')),
 (2, 'South Africa', Decimal('217601.01')),
 (7, 'Switzerland', Decimal('29281.62')),
 (6, 'Myanmar', Decimal('21840.84')),
 (5, 'Tonga', Decimal('11889.42')),
 (1, 'Bulgaria', Decimal('15760.62')),
 (6, 'Finland', Decimal('10920.42')),
 (2, 'Taiwan', Decimal('197819.10')),
 (6, 'Sri Lanka', Decimal('10920.42')),
 (7, 'Angola', Decimal('19521.08')),
 (6, 'Austria', Decimal('32761.26')),
 (5, 'Netherlands', Decimal('59447.10')),
 (1, 'Romania', Decimal('15760.62')),
 (1, 'Hong Kong', Decimal('7880.31')),
 (1, 'Tonga', Decimal('7880.31')),
 (1, 'Lithuania', Decimal('7880.31')),
 (2, 'Poland', Decimal('158255.28')),
 (4, 'China', Decimal('2082741.53')),
 (3, 'Japan', Decimal('1094405.71')),
 (6, 'Turkey', Decimal('163806.30')),
 (5, 'Czech Republic', Decimal('11889.42')),
 (1, 'Netherlands', Decimal('39401.55')),
 (6, 'Mozambique', Decimal('32761.26')),
 (7, 'Malaysia', Decimal('29281.62')),
 (6, 'Venezuela', Decimal('76442.94')),
 (5, 'Germany', Decimal('83225.94')),
 (3, 'Indonesia', Decimal('494247.74')),
 (5, 'Lithuania', Decimal('11889.42')),
 (5, 'Mexico', Decimal('356682.60')),
 (6, 'Thailand', Decimal('32761.26')),
 (7, 'Gambia', Decimal('9760.54')),
 (7, 'Vietnam', Decimal('58563.24')),
 (6, 'Taiwan', Decimal('109204.20')),
 (6, 'Sweden', Decimal('10920.42')),
 (4, 'Anguilla', Decimal('39297.01')),
 (3, 'Russian Federation', Decimal('988495.48')),
 (4, 'United States', Decimal('1414692.36')),
 (2, 'Brazil', Decimal('553893.48')),
 (5, 'Russian Federation', Decimal('332903.76')),
 (7, 'Bolivia', Decimal('19521.08')),
 (2, 'Hungary', Decimal('19781.91')),
 (5, 'Bahrain', Decimal('11889.42')),
 (3, 'Congo, The Democratic Republic of the', Decimal('70606.82')),
 (7, 'Sri Lanka', Decimal('9760.54')),
 (7, 'South Korea', Decimal('48802.70')),
 (4, 'Ukraine', Decimal('235782.06')),
 (4, 'Russian Federation', Decimal('1100316.28')),
 (3, 'Egypt', Decimal('211820.46')),
 (3, 'Hong Kong', Decimal('35303.41')),
 (7, 'France', Decimal('39042.16')),
 (5, 'Angola', Decimal('23778.84')),
 (5, 'Ethiopia', Decimal('11889.42')),
 (4, 'Philippines', Decimal('785940.20')),
 (5, 'Congo, The Democratic Republic of the', Decimal('23778.84')),
 (5, 'Argentina', Decimal('154562.46')),
 (2, 'New Zealand', Decimal('19781.91')),
 (2, 'Cambodia', Decimal('39563.82')),
 (2, 'Ukraine', Decimal('118691.46')),
 (3, 'Brazil', Decimal('988495.48')),
 (6, 'Ukraine', Decimal('65522.52')),
 (3, 'Ukraine', Decimal('211820.46')),
 (7, 'Germany', Decimal('68323.78')),
 (6, 'Sudan', Decimal('21840.84')),
 (6, 'Bahrain', Decimal('10920.42')),
 (2, 'Liechtenstein', Decimal('19781.91')),
 (6, 'Nepal', Decimal('10920.42')),
 (6, 'Egypt', Decimal('65522.52')),
 (2, 'Senegal', Decimal('19781.91')),
 (1, 'Greece', Decimal('15760.62')),
 (7, 'Algeria', Decimal('29281.62')),
 (6, 'Tuvalu', Decimal('10920.42')),
 (5, 'Romania', Decimal('23778.84')),
 (3, 'Czech Republic', Decimal('35303.41')),
 (2, 'Brunei', Decimal('19781.91')),
 (5, 'Slovakia', Decimal('11889.42')),
 (7, 'Virgin Islands, U.S.', Decimal('9760.54')),
 (3, 'New Zealand', Decimal('35303.41')),
 (2, 'Faroe Islands', Decimal('19781.91')),
 (5, 'Saint Vincent and the Grenadines', Decimal('11889.42')),
 (3, 'Netherlands', Decimal('176517.05')),
 (5, 'Liechtenstein', Decimal('11889.42')),
 (5, 'Turkmenistan', Decimal('11889.42')),
 (6, 'Madagascar', Decimal('10920.42')),
 (1, 'Tunisia', Decimal('7880.31')),
 (5, 'Iran', Decimal('95115.36')),
 (5, 'Belarus', Decimal('23778.84')),
 (2, 'Madagascar', Decimal('19781.91')),
 (5, 'Nigeria', Decimal('154562.46')),
 (2, 'South Korea', Decimal('98909.55')),
 (3, 'Finland', Decimal('35303.41')),
 (2, 'Netherlands', Decimal('98909.55')),
 (3, 'Moldova', Decimal('35303.41')),
 (5, 'Sudan', Decimal('23778.84')),
 (6, 'Armenia', Decimal('10920.42')),
 (6, 'North Korea', Decimal('10920.42')),
 (4, 'Tonga', Decimal('39297.01')),
 (3, 'Thailand', Decimal('105910.23')),
 (1, 'Mozambique', Decimal('23640.93')),
 (3, 'Kenya', Decimal('70606.82')),
 (1, 'American Samoa', Decimal('7880.31')),
 (1, 'Paraguay', Decimal('23640.93')),
 (6, 'Bolivia', Decimal('21840.84')),
 (5, 'Philippines', Decimal('237788.40')),
 (2, 'Oman', Decimal('39563.82')),
 (4, 'Bulgaria', Decimal('78594.02')),
 (4, 'Switzerland', Decimal('117891.03')),
 (7, 'North Korea', Decimal('9760.54')),
 (6, 'Cambodia', Decimal('21840.84')),
 (4, 'Malaysia', Decimal('117891.03')),
 (7, 'Venezuela', Decimal('68323.78')),
 (7, 'Greenland', Decimal('9760.54')),
 (5, 'Faroe Islands', Decimal('11889.42')),
 (4, 'Japan', Decimal('1218207.31')),
 (4, 'India', Decimal('2357820.60')),
 (6, 'Tunisia', Decimal('10920.42')),
 (5, 'Malawi', Decimal('11889.42')),
 (4, 'Colombia', Decimal('235782.06')),
 (7, 'Oman', Decimal('19521.08')),
 (5, 'Afghanistan', Decimal('11889.42')),
 (2, 'Sri Lanka', Decimal('19781.91')),
 (2, 'Ecuador', Decimal('59345.73')),
 (4, 'Hong Kong', Decimal('39297.01')),
 (7, 'Netherlands', Decimal('48802.70')),
 (3, 'French Guiana', Decimal('35303.41')),
 (1, 'United States', Decimal('283691.16')),
 (1, 'Egypt', Decimal('47281.86')),
 (7, 'Slovakia', Decimal('9760.54')),
 (6, 'Greece', Decimal('21840.84')),
 (3, 'Ethiopia', Decimal('35303.41')),
 (1, 'Switzerland', Decimal('23640.93')),
 (5, 'United Arab Emirates', Decimal('35668.26')),
 (4, 'American Samoa', Decimal('39297.01')),
 (7, 'Japan', Decimal('302576.74')),
 (2, 'Bolivia', Decimal('39563.82')),
 (1, 'New Zealand', Decimal('7880.31')),
 (1, 'Sweden', Decimal('7880.31')),
 (6, 'France', Decimal('43681.68')),
 (2, 'Saint Vincent and the Grenadines', Decimal('19781.91')),
 (2, 'China', Decimal('1048441.23')),
 (6, 'Malawi', Decimal('10920.42')),
 (5, 'Sri Lanka', Decimal('11889.42')),
 (6, 'Belarus', Decimal('21840.84')),
 (2, 'Yugoslavia', Decimal('39563.82')),
 (7, 'Ukraine', Decimal('58563.24')),
 (3, 'Ecuador', Decimal('105910.23')),
 (5, 'American Samoa', Decimal('11889.42')),
 (4, 'Venezuela', Decimal('275079.07')),
 (5, 'Malaysia', Decimal('35668.26')),
 (6, 'Kuwait', Decimal('10920.42')),
 (6, 'Ethiopia', Decimal('10920.42')),
 (7, 'Thailand', Decimal('29281.62')),
 (4, 'Canada', Decimal('196485.05')),
 (1, 'Italy', Decimal('55162.17')),
 (1, 'Brunei', Decimal('7880.31')),
 (3, 'Puerto Rico', Decimal('70606.82')),
 (3, 'Angola', Decimal('70606.82')),
 (5, 'Poland', Decimal('95115.36')),
 (6, 'Italy', Decimal('76442.94')),
 (2, 'India', Decimal('1186914.60')),
 (2, 'Colombia', Decimal('118691.46')),
 (5, 'Italy', Decimal('83225.94')),
 (2, 'Lithuania', Decimal('19781.91')),
 (5, 'Bangladesh', Decimal('35668.26')),
 (3, 'Estonia', Decimal('35303.41')),
 (7, 'Tuvalu', Decimal('9760.54')),
 (7, 'Indonesia', Decimal('136647.56')),
 (2, 'Latvia', Decimal('39563.82')),
 (3, 'Algeria', Decimal('105910.23')),
 (6, 'Tonga', Decimal('10920.42')),
 (4, 'Saudi Arabia', Decimal('196485.05')),
 (6, 'Dominican Republic', Decimal('32761.26')),
 (5, 'Runion', Decimal('11889.42')),
 (7, 'French Guiana', Decimal('9760.54')),
 (7, 'Saudi Arabia', Decimal('48802.70')),
 (1, 'Greenland', Decimal('7880.31')),
 (2, 'United States', Decimal('712148.76')),
 (2, 'Finland', Decimal('19781.91')),
 (2, 'Iran', Decimal('158255.28')),
 (4, 'Yugoslavia', Decimal('78594.02')),
 (1, 'Peru', Decimal('31521.24')),
 (6, 'Congo, The Democratic Republic of the', Decimal('21840.84')),
 (5, 'French Polynesia', Decimal('23778.84')),
 (1, 'Runion', Decimal('7880.31')),
 (1, 'Bolivia', Decimal('15760.62')),
 (7, 'Brazil', Decimal('273295.12')),
 (1, 'Canada', Decimal('39401.55')),
 (7, 'Nauru', Decimal('9760.54')),
 (2, 'Pakistan', Decimal('98909.55')),
 (6, 'Cameroon', Decimal('21840.84')),
 (5, 'Armenia', Decimal('11889.42')),
 (3, 'Israel', Decimal('141213.64')),
 (3, 'Paraguay', Decimal('105910.23')),
 (4, 'Azerbaijan', Decimal('78594.02')),
 (6, 'New Zealand', Decimal('10920.42')),
 (6, 'Estonia', Decimal('10920.42')),
 (2, 'Anguilla', Decimal('19781.91')),
 (7, 'Canada', Decimal('48802.70')),
 (3, 'Vietnam', Decimal('211820.46')),
 (3, 'Saudi Arabia', Decimal('176517.05')),
 (2, 'Gambia', Decimal('19781.91')),
 (6, 'Nigeria', Decimal('141965.46')),
 (7, 'Cameroon', Decimal('19521.08')),
 (6, 'Greenland', Decimal('10920.42')),
 (2, 'Tunisia', Decimal('19781.91')),
 (2, 'Puerto Rico', Decimal('39563.82')),
 (4, 'Greece', Decimal('78594.02')),
 (3, 'India', Decimal('2118204.60')),
 (7, 'Azerbaijan', Decimal('19521.08')),
 (1, 'Latvia', Decimal('15760.62')),

<div class="p-Widget jp-RenderedHTMLCommon jp-RenderedHTML jp-mod-trusted jp-OutputArea-output jp-OutputArea-executeResult" data-mime-type="text/html"><table>
    <tbody><tr>
        <th>month</th>
        <th>country</th>
        <th>revenue</th>
    </tr>
    <tr>
        <td>1</td>
        <td>Australia</td>
        <td>2364.19</td>
    </tr>
    <tr>
        <td>1</td>
        <td>Canada</td>
        <td>2460.24</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Australia</td>
        <td>4895.10</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Canada</td>
        <td>4736.78</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Australia</td>
        <td>12060.33</td>
    </tr>
</tbody></table></div>

## Revenue Total, by Month, by Country, by Month & Country All in one shot

TODO: Write a query that calculates total revenue at the various grouping levels done above (total, by month, by country, by month & country) all at once using the grouping sets function. Your output should match the table below.

In [13]:
%%sql
SELECT dd.month, dc.country, sum(fs.sales_amount) as revenue
FROM dimdate dd 
JOIN factsales fs ON (dd.date_key = fs.date_key)
JOIN dimcustomer dc ON (fs.customer_key = fs.customer_key)
GROUP BY GROUPING SETS ((), dd.month, dc.country, (dd.month, dc.country));

 * postgresql://abbas:***@127.0.0.1:5432/pagila_star
872 rows affected.

[(None, None, Decimal('80764978.98')),
 (5, 'Myanmar', Decimal('23778.84')),
 (7, 'Myanmar', Decimal('19521.08')),
 (5, 'Puerto Rico', Decimal('23778.84')),
 (3, 'Iran', Decimal('282427.28')),
 (5, 'Nepal', Decimal('11889.42')),
 (3, 'Germany', Decimal('247123.87')),
 (4, 'New Zealand', Decimal('39297.01')),
 (6, 'United Arab Emirates', Decimal('32761.26')),
 (4, 'Cameroon', Decimal('78594.02')),
 (2, 'Holy See (Vatican City State)', Decimal('19781.91')),
 (7, 'India', Decimal('585632.40')),
 (5, 'Nauru', Decimal('11889.42')),
 (6, 'Indonesia', Decimal('152885.88')),
 (5, 'Sweden', Decimal('11889.42')),
 (1, 'Holy See (Vatican City State)', Decimal('7880.31')),
 (6, 'Brazil', Decimal('305771.76')),
 (4, 'Paraguay', Decimal('117891.03')),
 (1, 'Pakistan', Decimal('39401.55')),
 (5, 'Dominican Republic', Decimal('35668.26')),
 (5, 'Canada', Decimal('59447.10')),
 (3, 'Faroe Islands', Decimal('35303.41')),
 (7, 'Kazakstan', Decimal('19521.08')),
 (7, 'Runion', Decimal('9760.54')),
 (3, 'Lithuania', Decimal('35303.41')),
 (4, 'Brunei', Decimal('39297.01')),
 (7, 'Anguilla', Decimal('9760.54')),
 (6, 'Paraguay', Decimal('32761.26')),
 (6, 'Yugoslavia', Decimal('21840.84')),
 (3, 'Malaysia', Decimal('105910.23')),
 (4, 'Lithuania', Decimal('39297.01')),
 (3, 'Peru', Decimal('141213.64')),
 (7, 'Russian Federation', Decimal('273295.12')),
 (4, 'Peru', Decimal('157188.04')),
 (5, 'Turkey', Decimal('178341.30')),
 (7, 'Faroe Islands', Decimal('9760.54')),
 (6, 'Germany', Decimal('76442.94')),
 (3, 'Poland', Decimal('282427.28')),
 (2, 'Angola', Decimal('39563.82')),
 (7, 'Kenya', Decimal('19521.08')),
 (2, 'Turkey', Decimal('296728.65')),
 (6, 'American Samoa', Decimal('10920.42')),
 (3, 'Canada', Decimal('176517.05')),
 (1, 'Myanmar', Decimal('15760.62')),
 (4, 'Kenya', Decimal('78594.02')),
 (7, 'Dominican Republic', Decimal('29281.62')),
 (5, 'Mozambique', Decimal('35668.26')),
 (5, 'Chad', Decimal('11889.42')),
 (1, 'Saint Vincent and the Grenadines', Decimal('7880.31')),
 (4, 'Ethiopia', Decimal('39297.01')),
 (3, 'Bangladesh', Decimal('105910.23')),
 (2, 'Philippines', Decimal('395638.20')),
 (5, 'Gambia', Decimal('11889.42')),
 (1, 'Philippines', Decimal('157606.20')),
 (6, 'Slovakia', Decimal('10920.42')),
 (6, 'Puerto Rico', Decimal('21840.84')),
 (6, 'Bulgaria', Decimal('21840.84')),
 (7, 'Liechtenstein', Decimal('9760.54')),
 (7, 'Tunisia', Decimal('9760.54')),
 (4, 'France', Decimal('157188.04')),
 (3, 'Nigeria', Decimal('458944.33')),
 (1, 'France', Decimal('31521.24')),
 (1, 'Armenia', Decimal('7880.31')),
 (4, 'Pakistan', Decimal('196485.05')),
 (1, 'Tanzania', Decimal('23640.93')),
 (1, 'Venezuela', Decimal('55162.17')),
 (3, 'Mexico', Decimal('1059102.30')),
 (6, 'Senegal', Decimal('10920.42')),
 (6, 'Israel', Decimal('43681.68')),
 (5, 'Kuwait', Decimal('11889.42')),
 (4, 'Brazil', Decimal('1100316.28')),
 (5, 'Iraq', Decimal('11889.42')),
 (2, 'Iraq', Decimal('19781.91')),
 (4, 'Mozambique', Decimal('117891.03')),
 (4, 'Belarus', Decimal('78594.02')),
 (3, 'Slovakia', Decimal('35303.41')),
 (2, 'Bangladesh', Decimal('59345.73')),
 (6, 'Chad', Decimal('10920.42')),
 (7, 'South Africa', Decimal('107365.94')),
 (7, 'Mexico', Decimal('292816.20')),
 (3, 'Bolivia', Decimal('70606.82')),
 (1, 'Gambia', Decimal('7880.31')),
 (7, 'Belarus', Decimal('19521.08')),
 (3, 'Virgin Islands, U.S.', Decimal('35303.41')),
 (4, 'Cambodia', Decimal('78594.02')),
 (1, 'Morocco', Decimal('23640.93')),
 (2, 'Russian Federation', Decimal('553893.48')),
 (7, 'Yugoslavia', Decimal('19521.08')),
 (6, 'Colombia', Decimal('65522.52')),
 (5, 'Cameroon', Decimal('23778.84')),
 (4, 'Puerto Rico', Decimal('78594.02')),
 (7, 'Chad', Decimal('9760.54')),
 (7, 'Holy See (Vatican City State)', Decimal('9760.54')),
 (3, 'United Kingdom', Decimal('317730.69')),
 (2, 'Thailand', Decimal('59345.73')),
 (4, 'Israel', Decimal('157188.04')),
 (3, 'Tonga', Decimal('35303.41')),
 (6, 'Ecuador', Decimal('32761.26')),
 (1, 'Slovakia', Decimal('7880.31')),
 (7, 'Malawi', Decimal('9760.54')),
 (2, 'Bahrain', Decimal('19781.91')),
 (5, 'Saudi Arabia', Decimal('59447.10')),
 (2, 'Nauru', Decimal('19781.91')),
 (5, 'United States', Decimal('428019.12')),
 (3, 'Pakistan', Decimal('176517.05')),
 (2, 'Slovakia', Decimal('19781.91')),
 (2, 'Switzerland', Decimal('59345.73')),
 (6, 'Angola', Decimal('21840.84')),
 (3, 'Venezuela', Decimal('247123.87')),
 (1, 'North Korea', Decimal('7880.31')),
 (7, 'Finland', Decimal('9760.54')),
 (5, 'Madagascar', Decimal('11889.42')),
 (6, 'Chile', Decimal('32761.26')),
 (2, 'Congo, The Democratic Republic of the', Decimal('39563.82')),
 (2, 'Peru', Decimal('79127.64')),
 (1, 'Chile', Decimal('23640.93')),
 (2, 'Tanzania', Decimal('59345.73')),
 (7, 'Argentina', Decimal('126887.02')),
 (3, 'Bulgaria', Decimal('70606.82')),
 (6, 'Saudi Arabia', Decimal('54602.10')),
 (4, 'United Arab Emirates', Decimal('117891.03')),
 (3, 'Colombia', Decimal('211820.46')),
 (1, 'Cambodia', Decimal('15760.62')),
 (3, 'Taiwan', Decimal('353034.10')),
 (7, 'American Samoa', Decimal('9760.54')),
 (3, 'Italy', Decimal('247123.87')),
 (3, 'Sweden', Decimal('35303.41')),
 (1, 'Poland', Decimal('63042.48')),
 (1, 'Sudan', Decimal('15760.62')),
 (4, 'Mexico', Decimal('1178910.30')),
 (7, 'Ecuador', Decimal('29281.62')),
 (5, 'Azerbaijan', Decimal('23778.84')),
 (3, 'Zambia', Decimal('35303.41')),
 (1, 'Algeria', Decimal('23640.93')),
 (3, 'Liechtenstein', Decimal('35303.41')),
 (3, 'Runion', Decimal('35303.41')),
 (3, 'Hungary', Decimal('35303.41')),
 (6, 'United Kingdom', Decimal('98283.78')),
 (1, 'French Polynesia', Decimal('15760.62')),
 (5, 'North Korea', Decimal('11889.42')),
 (7, 'Tonga', Decimal('9760.54')),
 (4, 'Runion', Decimal('39297.01')),
 (6, 'Latvia', Decimal('21840.84')),
 (6, 'Kenya', Decimal('21840.84')),
 (4, 'Moldova', Decimal('39297.01')),
 (4, 'Chile', Decimal('117891.03')),
 (3, 'Mozambique', Decimal('105910.23')),
 (3, 'Nepal', Decimal('35303.41')),
 (2, 'Malawi', Decimal('19781.91')),
 (6, 'Iraq', Decimal('10920.42')),
 (6, 'China', Decimal('578782.26')),
 (7, 'Puerto Rico', Decimal('19521.08')),
 (3, 'China', Decimal('1871080.73')),
 (1, 'United Kingdom', Decimal('70922.79')),
 (6, 'Pakistan', Decimal('54602.10')),
 (6, 'Netherlands', Decimal('54602.10')),
 (1, 'Ecuador', Decimal('23640.93')),
 (6, 'Tanzania', Decimal('32761.26')),
 (3, 'Anguilla', Decimal('35303.41')),
 (1, 'India', Decimal('472818.60')),
 (3, 'Switzerland', Decimal('105910.23')),
 (2, 'Yemen', Decimal('79127.64')),
 (4, 'Bahrain', Decimal('39297.01')),
 (7, 'Madagascar', Decimal('9760.54')),
 (4, 'Sri Lanka', Decimal('39297.01')),
 (3, 'Belarus', Decimal('70606.82')),
 (6, 'Iran', Decimal('87363.36')),
 (1, 'Oman', Decimal('15760.62')),
 (6, 'Saint Vincent and the Grenadines', Decimal('10920.42')),
 (4, 'Gambia', Decimal('39297.01')),
 (5, 'Ecuador', Decimal('35668.26')),
 (5, 'Algeria', Decimal('35668.26')),
 (7, 'Austria', Decimal('29281.62')),
 (7, 'Italy', Decimal('68323.78')),
 (2, 'North Korea', Decimal('19781.91')),
 (6, 'Romania', Decimal('21840.84')),
 (3, 'French Polynesia', Decimal('70606.82')),
 (2, 'Sweden', Decimal('19781.91')),
 (2, 'Ethiopia', Decimal('19781.91')),
 (7, 'United Arab Emirates', Decimal('29281.62')),
 (2, 'Israel', Decimal('79127.64')),
 (4, 'Taiwan', Decimal('392970.10')),
 (7, 'Romania', Decimal('19521.08')),
 (7, 'Czech Republic', Decimal('9760.54')),
 (1, 'Mexico', Decimal('236409.30')),
 (3, 'Madagascar', Decimal('35303.41')),
 (4, 'Thailand', Decimal('117891.03')),
 (1, 'Malawi', Decimal('7880.31')),
 (7, 'Bahrain', Decimal('9760.54')),
 (1, 'Sri Lanka', Decimal('7880.31')),
 (3, 'Cambodia', Decimal('70606.82')),
 (7, 'Zambia', Decimal('9760.54')),
 (1, 'Kazakstan', Decimal('15760.62')),
 (7, 'Cambodia', Decimal('19521.08')),
 (5, 'Holy See (Vatican City State)', Decimal('11889.42')),
 (2, 'Zambia', Decimal('19781.91')),
 (7, 'Chile', Decimal('29281.62')),
 (2, 'Spain', Decimal('98909.55')),
 (5, 'Senegal', Decimal('11889.42')),
 (5, 'New Zealand', Decimal('11889.42')),
 (2, 'Egypt', Decimal('118691.46')),
 (4, 'Argentina', Decimal('510861.13')),
 (5, 'Pakistan', Decimal('59447.10')),
 (7, 'Egypt', Decimal('58563.24')),
 (2, 'Romania', Decimal('39563.82')),
 (2, 'Kuwait', Decimal('19781.91')),
 (2, 'Morocco', Decimal('59345.73')),
 (4, 'Senegal', Decimal('39297.01')),
 (6, 'Poland', Decimal('87363.36')),
 (6, 'Oman', Decimal('21840.84')),
 (4, 'Yemen', Decimal('157188.04')),
 (2, 'Canada', Decimal('98909.55')),
 (5, 'Peru', Decimal('47557.68')),
 (1, 'Bahrain', Decimal('7880.31')),
 (2, 'Virgin Islands, U.S.', Decimal('19781.91')),
 (6, 'Nauru', Decimal('10920.42')),
 (4, 'Estonia', Decimal('39297.01')),
 (2, 'Argentina', Decimal('257164.83')),
 (1, 'Puerto Rico', Decimal('15760.62')),
 (4, 'Turkey', Decimal('589455.15')),
 (4, 'Czech Republic', Decimal('39297.01')),
 (7, 'Israel', Decimal('39042.16')),
 (7, 'Morocco', Decimal('29281.62')),
 (2, 'Belarus', Decimal('39563.82')),
 (6, 'Mexico', Decimal('327612.60')),
 (4, 'Nepal', Decimal('39297.01')),
 (7, 'Philippines', Decimal('195210.80')),
 (2, 'Armenia', Decimal('19781.91')),
 (4, 'Armenia', Decimal('39297.01')),
 (6, 'Anguilla', Decimal('10920.42')),
 (1, 'Nauru', Decimal('7880.31')),
 (3, 'Sudan', Decimal('70606.82')),
 (5, 'Brunei', Decimal('11889.42')),
 (3, 'Morocco', Decimal('105910.23')),
 (7, 'Brunei', Decimal('9760.54')),
 (2, 'Bulgaria', Decimal('39563.82')),
 (3, 'Kazakstan', Decimal('70606.82')),
 (5, 'Hungary', Decimal('11889.42')),
 (6, 'Czech Republic', Decimal('10920.42')),
 (7, 'Peru', Decimal('39042.16')),
 (4, 'Sudan', Decimal('78594.02')),
 (2, 'French Guiana', Decimal('19781.91')),
 (7, 'Senegal', Decimal('9760.54')),
 (1, 'Moldova', Decimal('7880.31')),
 (1, 'Kenya', Decimal('15760.62')),
 (6, 'India', Decimal('655225.20')),
 (7, 'United Kingdom', Decimal('87844.86')),
 (1, 'Ukraine', Decimal('47281.86')),
 (4, 'Holy See (Vatican City State)', Decimal('39297.01')),
 (5, 'Zambia', Decimal('11889.42')),
 (4, 'North Korea', Decimal('39297.01')),
 (4, 'Bangladesh', Decimal('117891.03')),
 (3, 'Greenland', Decimal('35303.41')),
 (5, 'Kazakstan', Decimal('23778.84')),
 (4, 'Indonesia', Decimal('550158.14')),
 (3, 'Dominican Republic', Decimal('105910.23')),
 (7, 'Taiwan', Decimal('97605.40')),
 (4, 'Sweden', Decimal('39297.01')),
 (7, 'Turkmenistan', Decimal('9760.54')),
 (5, 'Yemen', Decimal('47557.68')),
 (3, 'South Korea', Decimal('176517.05')),
 (1, 'Finland', Decimal('7880.31')),
 (2, 'United Arab Emirates', Decimal('59345.73')),
 (2, 'Germany', Decimal('138473.37')),
 (5, 'Chile', Decimal('35668.26')),
 (5, 'Ukraine', Decimal('71336.52')),
 (4, 'Tuvalu', Decimal('39297.01')),
 (4, 'Ecuador', Decimal('117891.03')),
 (6, 'South Korea', Decimal('54602.10')),
 (1, 'Kuwait', Decimal('7880.31')),
 (3, 'Armenia', Decimal('35303.41')),
 (4, 'Greenland', Decimal('39297.01')),
 (1, 'Estonia', Decimal('7880.31')),
 (5, 'Yugoslavia', Decimal('23778.84')),
 (4, 'Iran', Decimal('314376.08')),
 (5, 'Egypt', Decimal('71336.52')),
 (3, 'United States', Decimal('1270922.76')),
 (4, 'Iraq', Decimal('39297.01')),
 (5, 'Brazil', Decimal('332903.76')),
 (2, 'American Samoa', Decimal('19781.91')),
 (1, 'Nigeria', Decimal('102444.03')),
 (4, 'Austria', Decimal('117891.03')),
 (4, 'Saint Vincent and the Grenadines', Decimal('39297.01')),
 (1, 'United Arab Emirates', Decimal('23640.93')),
 (7, 'French Polynesia', Decimal('19521.08')),
 (5, 'Greenland', Decimal('11889.42')),
 (2, 'Algeria', Decimal('59345.73')),
 (6, 'Gambia', Decimal('10920.42')),
 (6, 'United States', Decimal('393135.12')),
 (3, 'Tunisia', Decimal('35303.41')),
 (3, 'Turkey', Decimal('529551.15')),
 (3, 'Chad', Decimal('35303.41')),
 (2, 'South Africa', Decimal('217601.01')),
 (7, 'Switzerland', Decimal('29281.62')),
 (6, 'Myanmar', Decimal('21840.84')),
 (5, 'Tonga', Decimal('11889.42')),
 (1, 'Bulgaria', Decimal('15760.62')),
 (6, 'Finland', Decimal('10920.42')),
 (2, 'Taiwan', Decimal('197819.10')),
 (6, 'Sri Lanka', Decimal('10920.42')),
 (7, 'Angola', Decimal('19521.08')),
 (6, 'Austria', Decimal('32761.26')),
 (5, 'Netherlands', Decimal('59447.10')),
 (1, 'Romania', Decimal('15760.62')),
 (1, 'Hong Kong', Decimal('7880.31')),
 (1, 'Tonga', Decimal('7880.31')),
 (1, 'Lithuania', Decimal('7880.31')),
 (2, 'Poland', Decimal('158255.28')),
 (4, 'China', Decimal('2082741.53')),
 (3, 'Japan', Decimal('1094405.71')),
 (6, 'Turkey', Decimal('163806.30')),
 (5, 'Czech Republic', Decimal('11889.42')),
 (1, 'Netherlands', Decimal('39401.55')),
 (6, 'Mozambique', Decimal('32761.26')),
 (7, 'Malaysia', Decimal('29281.62')),
 (6, 'Venezuela', Decimal('76442.94')),
 (5, 'Germany', Decimal('83225.94')),
 (3, 'Indonesia', Decimal('494247.74')),
 (5, 'Lithuania', Decimal('11889.42')),
 (5, 'Mexico', Decimal('356682.60')),
 (6, 'Thailand', Decimal('32761.26')),
 (7, 'Gambia', Decimal('9760.54')),
 (7, 'Vietnam', Decimal('58563.24')),
 (6, 'Taiwan', Decimal('109204.20')),
 (6, 'Sweden', Decimal('10920.42')),
 (4, 'Anguilla', Decimal('39297.01')),
 (3, 'Russian Federation', Decimal('988495.48')),
 (4, 'United States', Decimal('1414692.36')),
 (2, 'Brazil', Decimal('553893.48')),
 (5, 'Russian Federation', Decimal('332903.76')),
 (7, 'Bolivia', Decimal('19521.08')),
 (2, 'Hungary', Decimal('19781.91')),
 (5, 'Bahrain', Decimal('11889.42')),
 (3, 'Congo, The Democratic Republic of the', Decimal('70606.82')),
 (7, 'Sri Lanka', Decimal('9760.54')),
 (7, 'South Korea', Decimal('48802.70')),
 (4, 'Ukraine', Decimal('235782.06')),
 (4, 'Russian Federation', Decimal('1100316.28')),
 (3, 'Egypt', Decimal('211820.46')),
 (3, 'Hong Kong', Decimal('35303.41')),
 (7, 'France', Decimal('39042.16')),
 (5, 'Angola', Decimal('23778.84')),
 (5, 'Ethiopia', Decimal('11889.42')),
 (4, 'Philippines', Decimal('785940.20')),
 (5, 'Congo, The Democratic Republic of the', Decimal('23778.84')),
 (5, 'Argentina', Decimal('154562.46')),
 (2, 'New Zealand', Decimal('19781.91')),
 (2, 'Cambodia', Decimal('39563.82')),
 (2, 'Ukraine', Decimal('118691.46')),
 (3, 'Brazil', Decimal('988495.48')),
 (6, 'Ukraine', Decimal('65522.52')),
 (3, 'Ukraine', Decimal('211820.46')),
 (7, 'Germany', Decimal('68323.78')),
 (6, 'Sudan', Decimal('21840.84')),
 (6, 'Bahrain', Decimal('10920.42')),
 (2, 'Liechtenstein', Decimal('19781.91')),
 (6, 'Nepal', Decimal('10920.42')),
 (6, 'Egypt', Decimal('65522.52')),
 (2, 'Senegal', Decimal('19781.91')),
 (1, 'Greece', Decimal('15760.62')),
 (7, 'Algeria', Decimal('29281.62')),
 (6, 'Tuvalu', Decimal('10920.42')),
 (5, 'Romania', Decimal('23778.84')),
 (3, 'Czech Republic', Decimal('35303.41')),
 (2, 'Brunei', Decimal('19781.91')),
 (5, 'Slovakia', Decimal('11889.42')),
 (7, 'Virgin Islands, U.S.', Decimal('9760.54')),
 (3, 'New Zealand', Decimal('35303.41')),
 (2, 'Faroe Islands', Decimal('19781.91')),
 (5, 'Saint Vincent and the Grenadines', Decimal('11889.42')),
 (3, 'Netherlands', Decimal('176517.05')),
 (5, 'Liechtenstein', Decimal('11889.42')),
 (5, 'Turkmenistan', Decimal('11889.42')),
 (6, 'Madagascar', Decimal('10920.42')),
 (1, 'Tunisia', Decimal('7880.31')),
 (5, 'Iran', Decimal('95115.36')),
 (5, 'Belarus', Decimal('23778.84')),
 (2, 'Madagascar', Decimal('19781.91')),
 (5, 'Nigeria', Decimal('154562.46')),
 (2, 'South Korea', Decimal('98909.55')),
 (3, 'Finland', Decimal('35303.41')),
 (2, 'Netherlands', Decimal('98909.55')),
 (3, 'Moldova', Decimal('35303.41')),
 (5, 'Sudan', Decimal('23778.84')),
 (6, 'Armenia', Decimal('10920.42')),
 (6, 'North Korea', Decimal('10920.42')),
 (4, 'Tonga', Decimal('39297.01')),
 (3, 'Thailand', Decimal('105910.23')),
 (1, 'Mozambique', Decimal('23640.93')),
 (3, 'Kenya', Decimal('70606.82')),
 (1, 'American Samoa', Decimal('7880.31')),
 (1, 'Paraguay', Decimal('23640.93')),
 (6, 'Bolivia', Decimal('21840.84')),
 (5, 'Philippines', Decimal('237788.40')),
 (2, 'Oman', Decimal('39563.82')),
 (4, 'Bulgaria', Decimal('78594.02')),
 (4, 'Switzerland', Decimal('117891.03')),
 (7, 'North Korea', Decimal('9760.54')),
 (6, 'Cambodia', Decimal('21840.84')),
 (4, 'Malaysia', Decimal('117891.03')),
 (7, 'Venezuela', Decimal('68323.78')),
 (7, 'Greenland', Decimal('9760.54')),
 (5, 'Faroe Islands', Decimal('11889.42')),
 (4, 'Japan', Decimal('1218207.31')),
 (4, 'India', Decimal('2357820.60')),
 (6, 'Tunisia', Decimal('10920.42')),
 (5, 'Malawi', Decimal('11889.42')),
 (4, 'Colombia', Decimal('235782.06')),
 (7, 'Oman', Decimal('19521.08')),
 (5, 'Afghanistan', Decimal('11889.42')),
 (2, 'Sri Lanka', Decimal('19781.91')),
 (2, 'Ecuador', Decimal('59345.73')),
 (4, 'Hong Kong', Decimal('39297.01')),
 (7, 'Netherlands', Decimal('48802.70')),
 (3, 'French Guiana', Decimal('35303.41')),
 (1, 'United States', Decimal('283691.16')),
 (1, 'Egypt', Decimal('47281.86')),
 (7, 'Slovakia', Decimal('9760.54')),
 (6, 'Greece', Decimal('21840.84')),
 (3, 'Ethiopia', Decimal('35303.41')),
 (1, 'Switzerland', Decimal('23640.93')),
 (5, 'United Arab Emirates', Decimal('35668.26')),
 (4, 'American Samoa', Decimal('39297.01')),
 (7, 'Japan', Decimal('302576.74')),
 (2, 'Bolivia', Decimal('39563.82')),
 (1, 'New Zealand', Decimal('7880.31')),
 (1, 'Sweden', Decimal('7880.31')),
 (6, 'France', Decimal('43681.68')),
 (2, 'Saint Vincent and the Grenadines', Decimal('19781.91')),
 (2, 'China', Decimal('1048441.23')),
 (6, 'Malawi', Decimal('10920.42')),
 (5, 'Sri Lanka', Decimal('11889.42')),
 (6, 'Belarus', Decimal('21840.84')),
 (2, 'Yugoslavia', Decimal('39563.82')),
 (7, 'Ukraine', Decimal('58563.24')),
 (3, 'Ecuador', Decimal('105910.23')),
 (5, 'American Samoa', Decimal('11889.42')),
 (4, 'Venezuela', Decimal('275079.07')),
 (5, 'Malaysia', Decimal('35668.26')),
 (6, 'Kuwait', Decimal('10920.42')),
 (6, 'Ethiopia', Decimal('10920.42')),
 (7, 'Thailand', Decimal('29281.62')),
 (4, 'Canada', Decimal('196485.05')),
 (1, 'Italy', Decimal('55162.17')),
 (1, 'Brunei', Decimal('7880.31')),
 (3, 'Puerto Rico', Decimal('70606.82')),
 (3, 'Angola', Decimal('70606.82')),
 (5, 'Poland', Decimal('95115.36')),
 (6, 'Italy', Decimal('76442.94')),
 (2, 'India', Decimal('1186914.60')),
 (2, 'Colombia', Decimal('118691.46')),
 (5, 'Italy', Decimal('83225.94')),
 (2, 'Lithuania', Decimal('19781.91')),
 (5, 'Bangladesh', Decimal('35668.26')),
 (3, 'Estonia', Decimal('35303.41')),
 (7, 'Tuvalu', Decimal('9760.54')),
 (7, 'Indonesia', Decimal('136647.56')),
 (2, 'Latvia', Decimal('39563.82')),
 (3, 'Algeria', Decimal('105910.23')),
 (6, 'Tonga', Decimal('10920.42')),
 (4, 'Saudi Arabia', Decimal('196485.05')),
 (6, 'Dominican Republic', Decimal('32761.26')),
 (5, 'Runion', Decimal('11889.42')),
 (7, 'French Guiana', Decimal('9760.54')),
 (7, 'Saudi Arabia', Decimal('48802.70')),
 (1, 'Greenland', Decimal('7880.31')),
 (2, 'United States', Decimal('712148.76')),
 (2, 'Finland', Decimal('19781.91')),
 (2, 'Iran', Decimal('158255.28')),
 (4, 'Yugoslavia', Decimal('78594.02')),
 (1, 'Peru', Decimal('31521.24')),
 (6, 'Congo, The Democratic Republic of the', Decimal('21840.84')),
 (5, 'French Polynesia', Decimal('23778.84')),
 (1, 'Runion', Decimal('7880.31')),
 (1, 'Bolivia', Decimal('15760.62')),
 (7, 'Brazil', Decimal('273295.12')),
 (1, 'Canada', Decimal('39401.55')),
 (7, 'Nauru', Decimal('9760.54')),
 (2, 'Pakistan', Decimal('98909.55')),
 (6, 'Cameroon', Decimal('21840.84')),
 (5, 'Armenia', Decimal('11889.42')),
 (3, 'Israel', Decimal('141213.64')),
 (3, 'Paraguay', Decimal('105910.23')),
 (4, 'Azerbaijan', Decimal('78594.02')),
 (6, 'New Zealand', Decimal('10920.42')),
 (6, 'Estonia', Decimal('10920.42')),
 (2, 'Anguilla', Decimal('19781.91')),
 (7, 'Canada', Decimal('48802.70')),
 (3, 'Vietnam', Decimal('211820.46')),
 (3, 'Saudi Arabia', Decimal('176517.05')),
 (2, 'Gambia', Decimal('19781.91')),
 (6, 'Nigeria', Decimal('141965.46')),
 (7, 'Cameroon', Decimal('19521.08')),
 (6, 'Greenland', Decimal('10920.42')),
 (2, 'Tunisia', Decimal('19781.91')),
 (2, 'Puerto Rico', Decimal('39563.82')),
 (4, 'Greece', Decimal('78594.02')),
 (3, 'India', Decimal('2118204.60')),
 (7, 'Azerbaijan', Decimal('19521.08')),

<div class="p-Widget jp-RenderedHTMLCommon jp-RenderedHTML jp-mod-trusted jp-OutputArea-output jp-OutputArea-executeResult" data-mime-type="text/html"><table>
    <tbody><tr>
        <th>month</th>
        <th>country</th>
        <th>revenue</th>
    </tr>
    <tr>
        <td>1</td>
        <td>Australia</td>
        <td>2364.19</td>
    </tr>
    <tr>
        <td>1</td>
        <td>Canada</td>
        <td>2460.24</td>
    </tr>
    <tr>
        <td>1</td>
        <td>None</td>
        <td>4824.43</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Australia</td>
        <td>4895.10</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Canada</td>
        <td>4736.78</td>
    </tr>
    <tr>
        <td>2</td>
        <td>None</td>
        <td>9631.88</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Australia</td>
        <td>12060.33</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Canada</td>
        <td>11826.23</td>
    </tr>
    <tr>
        <td>3</td>
        <td>None</td>
        <td>23886.56</td>
    </tr>
    <tr>
        <td>4</td>
        <td>Australia</td>
        <td>14136.07</td>
    </tr>
    <tr>
        <td>4</td>
        <td>Canada</td>
        <td>14423.39</td>
    </tr>
    <tr>
        <td>4</td>
        <td>None</td>
        <td>28559.46</td>
    </tr>
    <tr>
        <td>5</td>
        <td>Australia</td>
        <td>271.08</td>
    </tr>
    <tr>
        <td>5</td>
        <td>Canada</td>
        <td>243.10</td>
    </tr>
    <tr>
        <td>5</td>
        <td>None</td>
        <td>514.18</td>
    </tr>
    <tr>
        <td>None</td>
        <td>None</td>
        <td>67416.51</td>
    </tr>
    <tr>
        <td>None</td>
        <td>Australia</td>
        <td>33726.77</td>
    </tr>
    <tr>
        <td>None</td>
        <td>Canada</td>
        <td>33689.74</td>
    </tr>
</tbody></table></div>

In [ ]:
#Notice that in the above cell, we could  replace GROUP BY GROUPING SETS ((), dd.month, dc.country, (dd.month, dc.country)); with the following

#GROUP BY cube (dd.month, dc.country);

#They both do the same thing.

#The latter does 0, 1 and 2 grouping combination just like we have explicitly stated it in the former